name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.3.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Common
  cupertino_icons: ^1.0.4
  nb_utils: ^4.5.2
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0

  #Google Font
  google_fonts: ^2.3.3

  #Icon
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.0.3

  #Image
  image_picker: ^0.8.5+3
  photo_view: ^0.13.0
  file_picker: ^4.5.1
  cached_network_image: ^3.2.1

  #Other
  date_time_picker: 2.1.0
  url_launcher: ^6.1.2
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.3
  flutter_staggered_animations: 1.0.0
  flutter_custom_tabs: ^1.0.4

  # Package Info
  package_info: ^2.0.2

  # Permission
  permission_handler: ^9.2.0

  #Social Login
  google_sign_in: ^5.3.1

  # Firebase
  firebase_crashlytics: ^2.8.0
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  firebase_storage: ^10.2.16
  firebase_remote_config: ^2.0.8
  cloud_firestore: ^3.1.15
  paginate_firestore: ^1.0.3+1
  flutter_html: ^3.0.0-alpha.3

  # PAYMENTS
  razorpay_flutter: ^1.3.0
  flutterwave_standard: 1.0.3
  flutterwave: ^1.0.1
  flutter_stripe: ^3.0.0

  ## Map
  google_maps_flutter: ^2.1.5
  geolocator: ^8.2.1
  geocoding: ^2.0.4

  #Push Notification
  onesignal_flutter: ^3.3.0

  # Mobx
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  modal_bottom_sheet: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - images/icons/
    - images/
    - images/flag/
    - images/app_images/
    - images/icons/
